version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/Users/admin/git/my-projects/demo-spring-webflux-kotlin-coroutines/docker-compose/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/Users/admin/git/my-projects/demo-spring-webflux-kotlin-coroutines/docker-compose/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "55681:55681"
