receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  azuremonitor:
    instrumentation_key: "<Instrumentation_Key>"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [azuremonitor]
